### ISSUE TITLE
Exception “OverflowError: Python int too large […]” fails

### ISSUE THREAD

**Issue by kseistrup** [friendly-traceback/friendly-traceback#105]
**With** `friendly_traceback` 0.5.1; `friendly` 0.5.2:

```py
>>> sys.version_info
sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)
>>> lotsoffun = range(1<<10000)
>>> len(lotsoffun)
Exception raised by friendly-traceback. Please report this case.
```

**Without** friendliness:

```py
>>> lotsoffun = range(1<<10000)
>>> len(lotsoffun)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C ssize_t
```

```sh
$ uname -a
Linux home 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux
```

**Comment by kseistrup** [comment]
**PS**: Inspired by https://twitter.com/bbelderbos/status/1479349250500829184

**Comment by aroberge** [comment]
Thanks for the report. This looks like a bit of a challenge to handle...  I'll have a look right away.

**Comment by aroberge** [comment]
Fixed. You will need `python -m pip install --upgrade friendly_traceback` to test it.

The problem arises when I attempt to show the value of all the interesting objects. If I determine that an object is too large to print (for example: a long list), I show a shortened version of that object and I show its length.  In this case, when computing the length, I was raising another OverflowError.

Below is the new output.

```
Traceback (most recent call last):

  File "HOME:\github\friendly-traceback\ignore2.py", line 2, in <module>
    len(huge)
OverflowError: Python int too large to convert to C ssize_t

    An `OverflowError` is raised when the result of an arithmetic operation
    is too large to be handled by the computer's processor.

    Exception raised on line 2 of file HOME:\github\friendly-traceback\ignore2.py.

       1: huge = range(1<<10000)
    -->2: len(huge)

            huge:  range(0, ...)
                   len(huge): Object too large to be processed by Python.

            len:  <builtin function len>
```

**Comment by kseistrup** [comment]
Thanks for the fast response.
