### ISSUE TITLE
Highligting of entire line is wrong in some cases

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#119]
Consider
```
def test():
    alpha1 = 1
    alpha2 += 1

test()
```
Here is the result, which is clearly wrong as
1. it points to the same line for where the program stopped and the exception was raised
2. the indentation is highlighted.

```
Traceback (most recent call last):
  File "HOME:\github\friendly-traceback\ignore.py", line 5, in <module>
    test()
  File "HOME:\github\friendly-traceback\ignore.py", line 3, in test
    alpha2 += 1
UnboundLocalError: local variable 'alpha2' referenced before assignment

        Did you mean `alpha1`?

...

    Execution stopped on line 5 of file HOME:\github\friendly-traceback\ignore.py.

       1: def test():
       2:     alpha1 = 1
    -->3:     alpha2 += 1
          ^^^^^^^^^^^^^^^

    Exception raised on line 3 of file HOME:\github\friendly-traceback\ignore.py.

       1: def test():
       2:     alpha1 = 1
    -->3:     alpha2 += 1
          ^^^^^^^^^^^^^^^

**Comment by aroberge** [comment]
Fixed one problem:
```
    Execution stopped on line 5 of file HOME:\github\friendly-traceback\ignore.py.

       1: def test():
       2:     alpha1 = 1
       3:     alpha2 += 1
       4:
    -->5: test()
          ^^^^^^

            test:  <function test>

    Exception raised on line 3 of file HOME:\github\friendly-traceback\ignore.py.

       1: def test():
       2:     alpha1 = 1
    -->3:     alpha2 += 1
          ^^^^^^^^^^^^^^^
```

**Comment by aroberge** [comment]
Fixed the other, even with comment present:
```
    Execution stopped on line 5 of file HOME:\github\friendly-traceback\ignore.py.

       1: def test():
       2:     alpha1 = 1
       3:     alpha2 += 1 # comment
       4:
    -->5: test()
          ^^^^^^

            test:  <function test>

    Exception raised on line 3 of file HOME:\github\friendly-traceback\ignore.py.

       1: def test():
       2:     alpha1 = 1
    -->3:     alpha2 += 1 # comment
              ^^^^^^^^^^^
```
