### ISSUE TITLE
Do not create inexisting paths for fake files

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#120]
Consider the following:
```python
code = compile("1/0", "fake_file", "exec")
exec(code)
```
Running this with friendly-traceback yields:
```
> python -m friendly_traceback ignore.py

Traceback (most recent call last):
  File "HOME:\github\friendly-traceback\ignore.py", line 2, in <module>
    exec(code)
  File "HOME:\github\friendly-traceback\fake_file", line 1, in <module>

ZeroDivisionError: division by zero
```
"fake_file" has been treated as though it was found in the CWD, even though it does not exist.

**Comment by aroberge** [comment]
New version:
```
> python -m friendly_traceback ignore.py

Traceback (most recent call last):
  File "HOME:\github\friendly-traceback\ignore.py", line 2, in <module>
    exec(code)
  File "fake_file", line 1, in <module>

ZeroDivisionError: division by zero
```
