### ISSUE TITLE
Revise message for ZeroDivisionError when source is not available.

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#122]
Consider the following:
```
> python -m friendly_traceback ignore.py

Traceback (most recent call last):
  File "HOME:\github\friendly-traceback\ignore.py", line 2, in <module>
    exec(code)
  File "fake_file", line 1, in <module>

ZeroDivisionError: division by zero

    A `ZeroDivisionError` occurs when you are attempting to divide a value
    by zero either directly or by using some other mathematical operation.

    The following mathematical expression includes a division by zero:




    Execution stopped on line 2 of file HOME:\github\friendly-traceback\ignore.py.

       1: code = compile("1/0", "fake_file", "exec")
    -->2: exec(code)
          ^^^^^^^^^^

            code:  <code object <module>>
            exec:  <builtin function exec>

    Exception raised on line 1 of file fake_file.
```
There is no mathematical expression that is shown!

**Comment by aroberge** [comment]
New version:
```
    A `ZeroDivisionError` occurs when you are attempting to divide a value
    by zero either directly or by using some other mathematical operation.

    The following mathematical expression includes a division by zero:

        <'expression not found'>

    Execution stopped on line 2 of file HOME:\github\friendly-traceback\ignore.py.

       1: code = compile("1/0", "fake_file", "exec")
    -->2: exec(code)
          ^^^^^^^^^^

            code:  <code object <module>>
            exec:  <builtin function exec>

    Exception raised on line 1 of file fake_file.

fake_file is not a regular Python file whose contents can be analyzed.
```
I used quotes in addition to `<...>` for nicer formatting with friendly (using Rich).
