### ISSUE TITLE
Can't set attribute - two types of cases

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#123]
See https://mail.python.org/archives/list/python-ideas@python.org/thread/NG3LNNF4LLDUOZS5UQS53HESWRIHHGXI/#NG3LNNF4LLDUOZS5UQS53HESWRIHHGXI for a discussion.

Two potential cases:

```
>>> Point = namedtuple('point', ('x', 'y'))
>>> p = Point(2, 3)
>>> p.x = 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't set attribute
```

And

```
>>> class C:
...     @property
...     def x():
...         return 3
...
>>> C().x = 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't set attribute 'x'
```

Include various sub-cases such as using `setattr` instead of a regular assignment, or having an explicit instance in the property case.

**Comment by alexmojaki** [comment]
```python
import _collections
import ast
from collections import namedtuple

import executing
import pure_eval


def check(tb):
  node = executing.Source.executing(tb).node
  print(ast.dump(node))
  assert isinstance(node, ast.Attribute)
  assert isinstance(node.ctx, ast.Store)

  evaluator = pure_eval.Evaluator.from_frame(tb.tb_frame)
  value = evaluator[node.value]
  attr = node.attr
  print(value, attr)

  cls = type(value)
  descriptor = getattr(cls, attr)

  if isinstance(descriptor, property):
    print("@property")
    assert descriptor.fset is None
  else:
    print("namedtuple")
    assert isinstance(descriptor, _collections._tuplegetter)

Point = namedtuple('point', ('x', 'y'))
p = Point(2, 3)

try:
  p.x = 1
except AttributeError as e:
  check(e.__traceback__)


class C:
  @property
  def y():
    return 3

c = C()
try:
  c.y = 4
except AttributeError as e:
  check(e.__traceback__)
```

**Comment by aroberge** [comment]
Thanks @alexmojaki for the suggestion.
