### ISSUE TITLE
SyntaxError shown at wrong location

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#156]
Consider the following exemple:
```
a = "hello" + """world
     continuing
```
With Python 3.9, we get the following:
```
  File "C:\Users\Andre\github\friendly-traceback\ignore.py", line 4
         continuing
                   ^
SyntaxError: EOF while scanning triple-quoted string literal
```
Meanwhile, this is what we get with `friendly_traceback`.
```
  File "HOME:\github\friendly-traceback\ignore.py", line 3
    a = "hello" + """world
     continuing
                                           ^
SyntaxError: EOF while scanning triple-quoted string literal

    A `SyntaxError` occurs when Python cannot understand your code.

    Python could not understand the code in the file
    'HOME:\github\friendly-traceback\ignore.py'


       1| a = "hello" + """world
       2|

    You started writing a triple-quoted string but never wrote
    the triple quotes needed to end the string.
```
The traceback includes two lines, with the caret `^` pointing at the wrong location.
The processed result does not even show where the error occurred and includes an empty second line.

**Comment by aroberge** [comment]
This is the comparable situation when using Python 3.10
```
> python ignore.py
  File "C:\Users\Andre\github\friendly-traceback\ignore.py", line 1
    a = "hello" + """world
                  ^
SyntaxError: unterminated triple-quoted string literal (detected at line 2)

(venv-friendly-traceback-3.10) C:\Users\Andre\github\friendly-traceback
> python -m friendly_traceback ignore.py

Traceback (most recent call last):
  File "HOME:\github\friendly-traceback\ignore.py", line 1
    a = "hello" + """world
                  ^
SyntaxError: unterminated triple-quoted string literal (detected at line 3)

    A `SyntaxError` occurs when Python cannot understand your code.

    Python could not understand the code in the file
    'HOME:\github\friendly-traceback\ignore.py'
    at the location indicated.

       1| a = "hello" + """world
                      ^

    You started writing a triple-quoted string but never wrote
    the triple quotes needed to end the string.
```

**Comment by aroberge** [comment]
This is now fixed. For example, with Python 3.10:
```
(venv-friendly-traceback-3.10) C:\Users\Andre\github\friendly-traceback
> python -m friendly_traceback ignore.py

Traceback (most recent call last):
  File "HOME:\github\friendly-traceback\ignore.py", line 1
    a = "hello" + """world
                  ^
SyntaxError: unterminated triple-quoted string literal (detected at line 2)

    A `SyntaxError` occurs when Python cannot understand your code.

    Python could not understand the code in the file
    'HOME:\github\friendly-traceback\ignore.py'
    at the location indicated.

       1| a = "hello" + """world
                        ^^^^^^^^

    You started writing a triple-quoted string but never wrote
    the triple quotes needed to end the string.
```
And with Python 3.6 (an other extreme):
```
Traceback (most recent call last):
  File "HOME:\github\friendly-traceback\ignore.py", line 2
    a = "hello" + """world
     continuing
                                          ^
SyntaxError: EOF while scanning triple-quoted string literal

    A `SyntaxError` occurs when Python cannot understand your code.

    Python could not understand the code in the file
    'HOME:\github\friendly-traceback\ignore.py'
    at the location indicated.

       1| a = "hello" + """world
                        ^^^^^^^^

    You started writing a triple-quoted string but never wrote
    the triple quotes needed to end the string.
```
