### ISSUE TITLE
Exception in friendly-traceback when __repr__ return non-string objects.

### ISSUE THREAD

**Issue by JulienPalard** [friendly-traceback/friendly-traceback#161]
A tricky one, but given `repro.py` as:

```python
class Foo:
    def __repr__(self):
        pass


def main():
    f = Foo()
    f.bar


main()
```

```
$ python -m friendly_traceback repro.py 
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/config.py", line 280, in get_traceback_info
    self.friendly_info[-1].compile_info()
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/core.py", line 419, in compile_info
    self.assign_location()
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/core.py", line 551, in assign_location
    self.locate_exception_raised(records[-1])
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/core.py", line 609, in locate_exception_raised
    var_info = info_variables.get_var_info(line, record.frame)
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/info_variables.py", line 237, in get_var_info
    objects = get_all_objects(line.strip(), frame)
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/info_variables.py", line 96, in get_all_objects
    repr_obj = repr(obj)
TypeError: __repr__ returned non-string (type NoneType)

Original exception was:
Traceback (most recent call last):
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/__main__.py", line 175, in main
    module_dict = runpy.run_path(args.source, run_name="__main__")
  File "/home/mdk/.local/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/mdk/.local/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/mdk/.local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "repro.py", line 11, in <module>
    main()
  File "repro.py", line 8, in main
    f.bar
AttributeError: 'Foo' object has no attribute 'bar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mdk/.local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mdk/.local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/__main__.py", line 196, in <module>
    main()
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/__main__.py", line 178, in main
    explain_traceback()
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/__init__.py", line 88, in explain_traceback
    session.explain_traceback(redirect=redirect)
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/config.py", line 204, in explain_traceback
    self.exception_hook(etype, value, tb, redirect=redirect)
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/config.py", line 233, in exception_hook
    info = self.get_traceback_info(etype, value, tb)
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/config.py", line 280, in get_traceback_info
    self.friendly_info[-1].compile_info()
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/core.py", line 419, in compile_info
    self.assign_location()
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/core.py", line 551, in assign_location
    self.locate_exception_raised(records[-1])
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/core.py", line 609, in locate_exception_raised
    var_info = info_variables.get_var_info(line, record.frame)
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/info_variables.py", line 237, in get_var_info
    objects = get_all_objects(line.strip(), frame)
  File "/home/mdk/clones/hkis/hkis-exercises/.venv/lib/python3.10/site-packages/friendly_traceback/info_variables.py", line 96, in get_all_objects
    repr_obj = repr(obj)
TypeError: __repr__ returned non-string (type NoneType)

```

**Comment by aroberge** [comment]
Thanks,

This should be easy to fix.  I thought I had fixed this before.

**Comment by aroberge** [comment]
Fixed.
```
C:\Users\Andre.Roberge>python -m friendly_traceback repro.py

Traceback (most recent call last):
  File "HOME:\repro.py", line 12, in <module>
    main()
  File "HOME:\repro.py", line 9, in main
    f.bar
AttributeError: 'Foo' object has no attribute 'bar'

    An `AttributeError` occurs when the code contains something like
        `object.x`
    and `x` is not a method or attribute (variable) belonging to `object`.

    The object `f` has no attribute named `bar`.

    Execution stopped on line 12 of file HOME:\repro.py.

        6| def main():
        7|     f = Foo()
        8|
        9|     f.bar
        :
    -->12| main()
           ^^^^^^

            main:  <function main>

    Exception raised on line 9 of file HOME:\repro.py.

       6| def main():
       7|     f = Foo()
       8|
    -->9|     f.bar
              ^^^^^

            f:  <class Foo>

```
