### ISSUE TITLE
Investigate replacing builtin exec

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#178]
When code is run with exec, its source is not available. When using friendly_traceback, it might be possible to replace exec in the builtin module by something like:

```
import builtins
old_exec = exec
def new_exec(source, ...):
    if is_code_object(source):
        return old_exec(source, ...)
    
    filename = "<friendly-exec-%d>" % next_id()
    source_cache.cache.add(filename, source)
    try:
        code = compile(source, filename, 'exec')
        old_exec(code, ...)
    except Exception:
        old_exec(source)
builtins.exec = new_exec
```
The inner code of `new_exec` is essentially what's done in the friendly console to make the source code available.

Perhaps this should be done only if enabled explicitly, so that it does not interfere with other projects such as futurecoder.  Or perhaps this should only be done with friendly, and not friendly_traceback.

@alexmojaki : What do you think?

**Comment by alexmojaki** [comment]
Doing this in friendly_traceback but requiring it to be enabled explicitly makes sense to me.

**Comment by aroberge** [comment]
After trying various versions, including when using iPython, I've concluded that replacing the builtin `exec` by a custom version that would then be used automatically was not a good idea. A better approach is to suggest the use of the custom version which I named `friendly_exec`.

Below is an example showing what it might look like in practice. Note that the version number shown for friendly_traceback has not been updated since making `friendly_exec` available in the console.

```
> python -m friendly_traceback --python

Friendly-traceback version 0.7.22. [Python version: 3.9.10]
Type 'Friendly' for help on special functions/methods.

>>> source = """
... a = 4
... b = 2
... c = 1 / (a - b**2)
... """
>>> exec(source)

Traceback (most recent call last):
  File "<friendly-console:2>", line 1, in <module>
    exec(source)
  File "<string>", line 4, in <module>

ZeroDivisionError: division by zero
>>> explain()

Traceback (most recent call last):
  File "<friendly-console:2>", line 1, in <module>
    exec(source)
  File "<string>", line 4, in <module>

ZeroDivisionError: division by zero

    A `ZeroDivisionError` occurs when you are attempting to divide a value
    by zero either directly or by using some other mathematical operation.

    Execution stopped on line `1` of file '<friendly-console:2>'.

    -->1| exec(source)
          ^^^^^^^^^^^^

            source:  '\na = 4\nb = 2\nc = 1 / (a - b**2)\n'
            exec:  <builtin function exec>

    Exception raised on line `4` of file '<string>'.

<string> is not a regular Python file whose contents can be analyzed.
If you used `exec`, consider using `friendly_exec` instead.
```

If we continue with `friendly_exec`, we have the following:
```
>>> friendly_exec(source)

Traceback (most recent call last):
  File "<friendly-console:4>", line 1, in <module>
    friendly_exec(source)
  File "FRIENDLY:\source_cache.py", line 111, in friendly_exec
    return true_exec(code, globals, locals)
  File "<friendly-exec-0>", line 4, in <module>
    c = 1 / (a - b**2)
ZeroDivisionError: division by zero
>>> explain()

Traceback (most recent call last):
  File "<friendly-console:4>", line 1, in <module>
    friendly_exec(source)
  File "FRIENDLY:\source_cache.py", line 111, in friendly_exec
    return true_exec(code, globals, locals)
  File "<friendly-exec-0>", line 4, in <module>
    c = 1 / (a - b**2)
ZeroDivisionError: division by zero

    A `ZeroDivisionError` occurs when you are attempting to divide a value
    by zero either directly or by using some other mathematical operation.

    You are dividing by the following term

         (a - b**2)

    which is equal to zero.

    Execution stopped on line `1` of file '<friendly-console:4>'.

    -->1| friendly_exec(source)
          ^^^^^^^^^^^^^^^^^^^^^

            friendly_exec:  <function friendly_exec>
            source:  '\na = 4\nb = 2\nc = 1 / (a - b**2)\n'

    Exception raised on line `4` of file '<friendly-exec-0>'.

       2| a = 4
       3| b = 2
    -->4| c = 1 / (a - b**2)
              ^^^^^^^^^^^^^^

            a:  4
            b:  2
            a - b**2:  0
            b**2:  4
```
