### ISSUE TITLE
More detailed output, no rich formatting, no friendly text

### ISSUE THREAD

**Issue by ShalokShalom** [friendly-traceback/friendly-traceback#221]
The code:
```py
from functools import partial
from dataclasses import dataclass
from expression import TaggedUnion, tag
import typing

data = partial(dataclass, slots=True, frozen= typing.TYPE_CHECKING)
def choice(cls): return type(cls.__name__, (TaggedUnion,) + cls.__bases__, cls.__dict__)

@data
class Details:
    Name: str
    Description: str
    
@data
class Item:
    Details: Details

@choice
class RoomID:
    RoomID: str

@choice
class Exit:
    PassableExit: str 
    LockedExit: str
    NoExit: str

@data
class Exits:
    North: Exit
    South: Exit
    East: Exit
    West: Exit

@data
class Room:
    ID: RoomID
    Details: Details
    Item: list[Item]
    Exits: Exits

@data
class Player:
    Details: Details
    Location: RoomID
    Inventory: list[Item]

@data
class World:
    Room: dict[RoomID, Room]
    Player: Player
```
friendly output:
```
 ╭─matthias@gramberg in ~/Documents/Python via  v3.10.10 took 36ms
[🔴] × python -m friendly devaspect.py


Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1698, in print
    extend(render(renderable, render_options))
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/panel.py", line 220, in __rich_console__
    lines = console.render_lines(renderable, child_options, style=style)
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1370, in render_lines
    lines = list(
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/segment.py", line 292, in split_and_crop_lines
    for segment in segments:
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/padding.py", line 97, in __rich_console__
    lines = console.render_lines(
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1370, in render_lines
    lines = list(
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/segment.py", line 292, in split_and_crop_lines
    for segment in segments:
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/markdown.py", line 560, in __rich_console__
    yield from console.render(element, context.options)
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/home/matthias/.local/lib/python3.10/site-packages/friendly/theme/friendly_rich.py", line 284, in _patch_heading
    if self.level == 3:
AttributeError: 'Heading' object has no attribute 'level'

Original exception was:
Traceback (most recent call last):
  File "/home/matthias/.local/lib/python3.10/site-packages/friendly/__main__.py", line 200, in main
    module_dict = runpy.run_path(args.source, run_name="__main__")
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "devaspect.py", line 19, in <module>
    class RoomID:
  File "devaspect.py", line 7, in choice
    def choice(cls): return type(cls.__name__, (TaggedUnion,) + cls.__bases__, cls.__dict__)
TypeError: type.__new__() argument 3 must be dict, not mappingproxy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/matthias/.local/lib/python3.10/site-packages/friendly/__main__.py", line 224, in <module>
    main()
  File "/home/matthias/.local/lib/python3.10/site-packages/friendly/__main__.py", line 203, in main
    explain_traceback()
  File "/home/matthias/.local/lib/python3.10/site-packages/friendly_traceback/__init__.py", line 151, in explain_traceback
    session.explain_traceback(redirect=redirect)
  File "/home/matthias/.local/lib/python3.10/site-packages/friendly_traceback/config.py", line 205, in explain_traceback
    self.exception_hook(etype, value, tb, redirect=redirect)
  File "/home/matthias/.local/lib/python3.10/site-packages/friendly_traceback/config.py", line 237, in exception_hook
    self.output_info(info, redirect=redirect)
  File "/home/matthias/.local/lib/python3.10/site-packages/friendly_traceback/config.py", line 256, in output_info
    self.write_err(explanation)
  File "/home/matthias/.local/lib/python3.10/site-packages/friendly/rich_formatters.py", line 249, in rich_writer
    session.console.print(md)
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1698, in print
    extend(render(renderable, render_options))
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/panel.py", line 220, in __rich_console__
    lines = console.render_lines(renderable, child_options, style=style)
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1370, in render_lines
    lines = list(
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/segment.py", line 292, in split_and_crop_lines
    for segment in segments:
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/padding.py", line 97, in __rich_console__
    lines = console.render_lines(
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1370, in render_lines
    lines = list(
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/segment.py", line 292, in split_and_crop_lines
    for segment in segments:
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/markdown.py", line 560, in __rich_console__
    yield from console.render(element, context.options)
  File "/home/matthias/.local/lib/python3.10/site-packages/rich/console.py", line 1330, in render
    for render_output in iter_render:
  File "/home/matthias/.local/lib/python3.10/site-packages/friendly/theme/friendly_rich.py", line 284, in _patch_heading
    if self.level == 3:
AttributeError: 'Heading' object has no attribute 'level'
```
normal output
```
 ╭─matthias@gramberg in ~/Documents/Python via  v3.10.10 took 148ms
[🔴] × python -m devaspect.py
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/matthias/Documents/Python/devaspect.py", line 19, in <module>
    class RoomID:
  File "/home/matthias/Documents/Python/devaspect.py", line 7, in choice
    def choice(cls): return type(cls.__name__, (TaggedUnion,) + cls.__bases__, cls.__dict__)
TypeError: type.__new__() argument 3 must be dict, not mappingproxy
```

**Comment by aroberge** [comment]
Could you tell me what version of Rich you are using? From the traceback, I suspect that you are using a newer version than what I have been using. Knowing that this is the case would help me to figure out how to fix it.

**Comment by ShalokShalom** [comment]
```
pip show rich
13.3.2
```

**Comment by aroberge** [comment]
Note to self: The change likely occurred in https://github.com/Textualize/rich/commit/a20c3d5468d02a55d309d454a800f402c32438bd where `level` was changed to `tag`, and I would need to replace
```
if self.level == 3
```
by something like
```
if hasattr(self, 'level'):
    if self.level == 3:
        ...
elif self.tag == 'h3':
    ...
```

**Comment by aroberge** [comment]
This should be fixed now. (New version uploaded to Pypi.)
Here is what it looks like:
![image](https://user-images.githubusercontent.com/629698/227017351-e8d1956f-78fb-40fc-a918-df01df2202a8.png)

Thank you very much for the report!
