### ISSUE TITLE
Trim traceback further.

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#46]
Consider the following example from different Python versions:

```python
Python 3.6.8 
>>> import collections
>>> collections.x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'collections' has no attribute 'x'
```
```python
Python 3.7.8
>>> import collections
>>> collections.x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\collections\__init__.py", line 55, in __getattr__
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'collections' has no attribute 'x'
```

```python
Python 3.8.10 
>>> import collections
>>> collections.x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\collections\__init__.py", line 55, in __getattr__
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'collections' has no attribute 'x'
```

```python
Python 3.9.5 
>>> import collections
>>> collections.x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Python39\lib\collections\__init__.py", line 68, in __getattr__
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'collections' has no attribute 'x'
```

```python
Python 3.10.0rc1 
>>> import collections
>>> collections.x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'collections' has no attribute 'x'
```

Python 3.6 and Python 3.10 do NOT show the line `raise ...` in `__init__.py`.  I believe that this results in a cleaner traceback, more useful for the end user.

Here's what it looks like when using friendly-traceback with Python 3.10 and 3.9.

```python
Friendly-traceback version 0.4.31. [Python version: 3.10.0rc1]
Type 'Friendly' for help on special functions/methods.

[1]: import collections

[2]: collections.x

Traceback (most recent call last):
  Code block [2], line 1, in <module>
    collections.x
AttributeError: module 'collections' has no attribute 'x'
```

```python
Friendly-traceback version 0.4.31. [Python version: 3.9.5]
Type 'Friendly' for help on special functions/methods.

[1]: import collections

[2]: collections.x

Traceback (most recent call last):
  Code block [2], line 1, in <module>
    collections.x
  File "PYTHON_LIB:\collections\__init__.py", line 68, in __getattr__
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'collections' has no attribute 'x'
```

Removing the line inside the Python library for `friendly_tb`, would allow the user to focus on their own code.

**Comment by aroberge** [comment]
Here what it looks like after the new exclusion:
```python
Friendly-traceback version 0.4.31. [Python version: 3.9.5]
Type 'Friendly' for help on special functions/methods.

[1]: import collections

[2]: collections.x

Traceback (most recent call last):
  Code block [2], line 1, in <module>
    collections.x
AttributeError: module 'collections' has no attribute 'x'
```
So, we now have the same output for all Python versions.

@hoefling @alexmojaki I'm making a change to exclude by default all files from the Python standard library - assuming that this is not going to create problems for your applications.  The idea is that when an error occur inside a Python library, the actual code (and variables) from that library is not shown to the end user.  This is already the case for all modules written in C.

Here's a longer example where much irrelevant output is suppressed.

**New version**
```python
Traceback (most recent call last):
  File "PYTHON_LIB:\collections\__init__.py", line 965, in pop
    return self.maps[0].pop(key, *args)
KeyError: 42

    During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TESTS:\runtime\test_key_error.py", line 62, in test_ChainMap
    d.pop(42)
KeyError: 'Key not found in the first mapping: 42'

A `KeyError` is raised when a value is not found as a
key in a Python dict or in a similar object.

The key `42` cannot be found in `d`, an object of type `ChainMap`.

Exception raised on line 62 of file TESTS:\runtime\test_key_error.py.

   59:     from collections import ChainMap
   60:     d = ChainMap({}, {})
   61:     try:
-->62:         d.pop(42)
   63:     except KeyError as e:

        d:  ChainMap({}, {})
        d.pop:  <bound method ChainMap.pop of ChainMap({}, {})>
```


**Previously*
```python
Traceback (most recent call last):
  File "PYTHON_LIB:\collections\__init__.py", line 1008, in pop
    return self.maps[0].pop(key, *args)
KeyError: 42

    During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TESTS:\runtime\test_key_error.py", line 62, in test_ChainMap
    d.pop(42)
  File "PYTHON_LIB:\collections\__init__.py", line 1010, in pop
    raise KeyError(f'Key not found in the first mapping: {key!r}')
KeyError: 'Key not found in the first mapping: 42'

A `KeyError` is raised when a value is not found as a
key in a Python dict or in a similar object.

The key `42` cannot be found in `d`, an object of type `ChainMap`.

Execution stopped on line 62 of file TESTS:\runtime\test_key_error.py.

   59:     from collections import ChainMap
   60:     d = ChainMap({}, {})
   61:     try:
-->62:         d.pop(42)
   63:     except KeyError as e:

        d:  ChainMap({}, {})
        d.pop:  <bound method ChainMap.pop of ChainMap({}, {})>

Exception raised on line 1010 of file PYTHON_LIB:\collections\__init__.py.

   1007:         try:
   1008:             return self.maps[0].pop(key, *args)
   1009:         except KeyError:
-->1010:             raise KeyError(f'Key not found in the first mapping: {key!r}')

        KeyError:  <class KeyError>
```
Note all the information from within `collections`__init__.py` in the last section (Exception raised ...) is no longer shown. It is still shown at the very beginning (as we have chained exceptions, some of which occur entirely within Python code, and no removal is done if it ends up suppressing everything).

**Comment by aroberge** [comment]
Since the beginning, both `python_tb()` and `friendly_tb()`  [corresponding respectively to `info["simulated_python_traceback"]` and `info["shortened_traceback"]` have been "trimmed" the same way by having frames specific to friendly-traceback removed.  The idea was that `python_tb()` should be identical to what the user would see if they were running their code with Python, and `friendly_tb()` would often be simplified (shorter filepaths, some lines not shown if the traceback was too long, etc.)

With the recent change, `python_tb()` can now be different from what the user would see using Python to run their code.
I should make some changes so that the further trimming is only done for `friendly_tb()`. This will require two different traceback procedures (or duplications of "records") compared with the single one currently used.

**Comment by hoefling** [comment]
This is change is welcomed from me, means less traceback trimming on our side. We are also using `friendly_tb()` exclusively, so not breaking for us.

**Comment by aroberge** [comment]
The previous commit implements the trimming of Python stdlib code ONLY for `friendly_tb()`. I need to do a few more tests.

@hoefling You mention having to do (additional?) traceback trimming for your project. If you think that `friendly_tb()` could be improved for this project, feel free to offer suggestions.
