### ISSUE TITLE
jinja2 template syntax error causes internal error

### ISSUE THREAD

**Issue by MrGreenTea** [friendly-traceback/friendly-traceback#73]
This small example reproduces the problem.

```py
import friendly
import jinja2


friendly.install()

environment = jinja2.Environment(loader=jinja2.FileSystemLoader("."))
template = environment.get_template("template.j2")
template.render()
```

the template file `template.j2`:
```jinja2
{{
```

I've noticed that the error happens inside `FrameInfo.stack_data()` when it tries to build the `FrameInfo` object for the frame in the `jinja2` template. This does not become a problem for other `jinja2` errors like `jinja2.exceptions.UndefinedError` when using
```py
environment = jinja2.Environment(
    loader=jinja2.FileSystemLoader("."),
    undefined=jinja2.StrictUndefined,
)
```

**Comment by aroberge** [comment]
Thanks for the report.  This appears to be a problem with one of the dependencies of friendly-traceback.  I will file an issue upstream.  Afterwards, I'll try to see if I can give a more informative error message.

```
> python -m friendly --debug

friendly-traceback: 0.4.59
friendly: 0.4.26
Python: 3.9.5
Type 'Friendly' for help on special functions/methods.

[1]: import jinja2

[2]: environment = jinja2.Environment(loader=jinja2.FileSystemLoader("."))

[3]: template = environment.get_template("template.j2")
Uncaught exception in TracebackData.
TokenError('EOF in multi-line statement', (4, 0))
no_information: new case to consider.
Friendly_traceback; please_report; new case to consider.

Traceback (most recent call last):
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\friendly_traceback\ft_console.py",
line 171, in runcode
    exec(code, self.locals)  # type: ignore
  File "<friendly-console:3>", line 1, in <module>
    template = environment.get_template("template.j2")
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\jinja2\environment.py", line 997,
in get_template
    return self._load_template(name, globals)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\jinja2\environment.py", line 958,
in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\jinja2\loaders.py", line 137, in
load
    code = environment.compile(source, name, filename)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\jinja2\environment.py", line 757,
in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\jinja2\environment.py", line 925,
in handle_exception
    raise rewrite_traceback_stack(source=source)
  File ".\template.j2", line 1, in template
    {{
jinja2.exceptions.TemplateSyntaxError: unexpected 'end of template'

    During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\executing\executing.py", line 286,
in executing
    args = executing_cache[key]
KeyError: (<code object template at 0x00000189817982F0, file ".\template.j2", line 1>, 1690094371568, 2)

    During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\friendly_traceback\ft_console.py",
line 171, in runcode
    exec(code, self.locals)  # type: ignore
  File "<friendly-console:3>", line 1, in <module>
    template = environment.get_template("template.j2")
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\jinja2\environment.py", line 997,
in get_template
    return self._load_template(name, globals)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\jinja2\environment.py", line 958,
in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\jinja2\loaders.py", line 137, in
load
    code = environment.compile(source, name, filename)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\jinja2\environment.py", line 757,
in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\jinja2\environment.py", line 925,
in handle_exception
    raise rewrite_traceback_stack(source=source)
  File ".\template.j2", line 1, in template
    {{
jinja2.exceptions.TemplateSyntaxError: unexpected 'end of template'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\executing\executing.py", line 286,
in executing
    args = executing_cache[key]
KeyError: (<code object template at 0x00000189817982F0, file ".\template.j2", line 1>, 1690094371568, 2)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\friendly_traceback\core.py", line
434, in __init__
    self.tb_data = TracebackData(etype, value, tb)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\friendly_traceback\core.py", line
72, in __init__
    self.records = self.get_records(tb)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\friendly_traceback\core.py", line
119, in get_records
    all_records = list(FrameInfo.stack_data(tb, collapse_repeated_frames=False))
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\stack_data\core.py", line 534, in
stack_data
    yield from map(mapper, stack)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\stack_data\core.py", line 531, in
mapper
    return cls(f, options)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\stack_data\core.py", line 496, in
__init__
    self.executing = Source.executing(frame_or_tb)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\executing\executing.py", line 320,
in executing
    args = find(source=cls.for_frame(frame), retry_cache=True)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\executing\executing.py", line 221,
in for_frame
    return cls.for_filename(frame.f_code.co_filename, frame.f_globals or {}, use_cache)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\executing\executing.py", line 239,
in for_filename
    result = source_cache[filename] = cls._for_filename_and_lines(filename, lines)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\executing\executing.py", line 250,
in _for_filename_and_lines
    result = source_cache[(filename, lines)] = cls(filename, lines)
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\stack_data\core.py", line 80, in
__init__
    self.asttokens()
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\executing\executing.py", line 364,
in asttokens
    return ASTTokens(
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\asttokens\asttokens.py", line 59,
in __init__
    self._tokens = list(self._generate_tokens(source_text))
  File "C:\Users\andre\friendly-traceback\friendly\venv-friendly-3.9\lib\site-packages\asttokens\asttokens.py", line 85,
in _generate_tokens
    for index, tok in enumerate(tokenize.generate_tokens(io.StringIO(text).readline)):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\tokenize.py", line 521, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (4, 0))

Fatal error - aborting
```

**Comment by aroberge** [comment]
Here is more info processed by Friendly in a nicer to read format:
```
    Execution stopped on line 534 of file LOCAL:\stack_data\core.py.

       530:         def mapper(f):
       531:             return cls(f, options)
       533:         if not collapse_repeated_frames:
    -->534:             yield from map(mapper, stack)
       535:             return

            mapper:  <function mapper> defined in <function FrameInfo.stack_data>
            stack:  [<traceback object at 0x04821128>, ...]
                    len(stack): 9

            map:  <class map>

    Exception raised on line 85 of code block LOCAL:\asttokens\asttokens.py.

       79:   def _generate_tokens(self, text):
       80:     """
       81:     Generates tokens for the given code.
       82:     """
       83:     # This is technically an undocumented API for Python3, but allows us to use the same API as for
       84:     # Python2. See http://stackoverflow.com/a/4952291/328565.
    -->85:     for index, tok in enumerate(tokenize.generate_tokens(io.StringIO(text).readline)):
       86:       tok_type, tok_str, start, end, line = tok

            index:  4
            text:  '{{\n\n\n'
            tok:  TokenInfo(type=61 (NL), string='\n', start=(3, 0), end=(3, 1), ...)
                  len(tok): 5

            global io:  <module io> from PYTHON_LIB:\io.py
            global tokenize:  <module tokenize> from PYTHON_LIB:\tokenize.py
            enumerate:  <class enumerate>
            index, tok:  (4, TokenInfo(type=61 (NL), string='\n', start=(3, 0), end=(3, 1), ...)
                         len(index, tok): 2

            io.StringIO:  <class _io.StringIO>
            tokenize.generate_tokens:  <function generate_tokens>
```

**Comment by aroberge** [comment]
This has been fixed in stack_data. Instead of seeing
```
> python issue_73.py
Internal problem in Friendly.
Please report this issue.
```
here is the new traceback for my local version that has stack_data updated to 0.1.2:
```
> python ignore_issue_73.py

Traceback (most recent call last):
  File "ignore_issue_73.py", line 9, in <module>
    template = environment.get_template("template.j2")
       ... More lines not shown. ...
  File "LOCAL:\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "template.j2", line 1, in template

TemplateSyntaxError: unexpected 'end of template'

    No information is known about this exception.
    Please report this example to
    https://github.com/friendly-traceback/friendly-traceback/issues/new
    If you are using a REPL, use `www('bug')` to do so.

    If you are using the Friendly console, use `www()` to
    do an Internet search for this particular case.

    Execution stopped on line 9 of file ignore_issue_73.py.

        5: friendly.install()
        6: ft.debug_helper.DEBUG = False
        8: environment = jinja2.Environment(loader=jinja2.FileSystemLoader("."))
    --> 9: template = environment.get_template("template.j2")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       10: template.render()

            environment:  <jinja2.environment.Environment object>
            environment.get_template:  <bound method Environment.get_template> of <jinja2.environment.Environment object>

    Exception raised on line 1 of file template.j2.

Problem: source of `C:\Users\andre\friendly-traceback\friendly\template.j2` is not available
```
I will keep this issue open as I want to be able to give a more informative message than
```
> python issue_73.py
Internal problem in Friendly.
Please report this issue.
```
for such cases.

**Comment by aroberge** [comment]
This is how such an issue would now be reported by Friendly/Friendly-traceback
```
Internal error caused by TokenError('EOF in multi-line statement', (4, 0))
Please report this issue.
The following package(s) used by friendly-traceback
appear in the full traceback, which may indicate
that one of them is the source of this error.
executing.py
stack_data
asttokens
```

**Comment by MrGreenTea** [comment]
Thanks for the quick response.
What I don't yet understand is why this does not happen for `jinja2.exceptions.UndefinedError`.
Here it looks like this:

```py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    sql_statement = template.render()
  File "LOCAL:/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "LOCAL:/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "template.j2", line 1, in top-level template code
    {{ a }}
UndefinedError: 'a' is undefined

    No information is known about this exception.
    Please report this example to
    https://github.com/friendly-traceback/friendly-traceback/issues/new
    If you are using a REPL, use `www('bug')` to do so.
    
    If you are using the Friendly console, use `www()` to
    do an Internet search for this particular case.
    
    Execution stopped on line 9 of file test.py.
    
       5: friendly.install()
       7: environment = jinja2.Environment(loader=jinja2.FileSystemLoader("."), undefined=jinja2.StrictUndefined)
       8: template = environment.get_template("template.j2")
    -->9: sql_statement = template.render()
                          ^^^^^^^^^^^^^^^^^

            template:  <Template 'template.j2>
            template.render:  <bound method Template.render> of <Template 'template.j2>
        
    Exception raised on line 1 of file template.j2.
    
    -->1: {{ a }}
```

**Comment by MrGreenTea** [comment]
Oh after testing with a more complex template it becomes clear. `{{ a }}` is valid python source that can be parsed without problem.

after changing the template to `F {{ a }}` for example I get as the last line `Problem: source of `template.j2` is not available`

**Comment by aroberge** [comment]
When I wrote previously about how such an error would appear, I was referring to the case where an Internal error occurred due to a problem in one of friendly-traceback's dependencies. Now that the problem has been fixed at the source (stack_data, a dependency of friendly-traceback, has been modified), the analysis can proceed without an internal error.

@MrGreenTea I assume, from your last comment, that the output is satisfactory. If not, please let me know how I should fix it.  Note that I do not plan, for now, to include custom exceptions (such as `UndefinedError`) from third party packages as I still have a lot cases to add from Python's standard exceptions.

**Comment by MrGreenTea** [comment]
Hey @aroberge I just got back to this. I've actually got it working with a small change to `FrameInfo._partial_source`.
There the lines are added from `s_lines[lineno -2 : lineno]`. If `lineno == 1` this causes the start of the slice to be `-1` and so it becomes this: `s_lines[-1:1]` which is always empty. When clamping the start `linenumber` to be at least 0 it actually works fine and the source of the template shows up in the output.

Would you be interested in a PR for this?
Literally the only change is on line 43 of `frame_info.py`:
```py
...
with_node_range = False
linenumber = max(lineno - 2, 0)  # This is the changed line
for line in s_lines[linenumber : lineno + 1]:
    ...
```

**Comment by MrGreenTea** [comment]
Please do, I won't make it until tomorrow :)

**Comment by aroberge** [comment]
Change made in repo. This will be included in the next version on pypi.org.
