### ISSUE TITLE
Infinite loop in explain_traceback

### ISSUE THREAD

**Issue by JulienPalard** [friendly-traceback/friendly-traceback#78]
Did not tried to diagnose it, #sry, so I just give you this:

```python
import time
import friendly_traceback

try:
    time.strptime("2020-01-01", "%d %m %Y")
except Exception as err:
    print(err)
    friendly_traceback.explain_traceback()
```

It gives:
```text
time data '2020-01-01' does not match format '%d %m %Y'

^C  # I have to kill it

Traceback (most recent call last):
  File "/home/mdk/clones/hkis/hkis-ansible/pouette.py", line 9, in <module>
    item = time.strptime("2020-01-01", "%d %m %Y")
  File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2020-01-01' does not match format '%d %m %Y'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mdk/clones/hkis/hkis-ansible/pouette.py", line 12, in <module>
    friendly_traceback.explain_traceback()
  File "/home/mdk/.local/lib/python3.9/site-packages/friendly_traceback/__init__.py", line 84, in explain_traceback
    session.explain_traceback(redirect=redirect)
  File "/home/mdk/.local/lib/python3.9/site-packages/friendly_traceback/config.py", line 174, in explain_traceback
    self.exception_hook(etype, value, tb, redirect=redirect)
  File "/home/mdk/.local/lib/python3.9/site-packages/friendly_traceback/config.py", line 209, in exception_hook
    self.friendly_info.append(core.FriendlyTraceback(etype, value, tb))
  File "/home/mdk/.local/lib/python3.9/site-packages/friendly_traceback/core.py", line 444, in __init__
    self.assign_tracebacks()
  File "/home/mdk/.local/lib/python3.9/site-packages/friendly_traceback/core.py", line 747, in assign_tracebacks
    python_tb = self.create_traceback(self.tb_data.python_records)
  File "/home/mdk/.local/lib/python3.9/site-packages/friendly_traceback/core.py", line 869, in create_traceback
    partial_source = record.partial_source  # noqa
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/utils.py", line 141, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mdk/.local/lib/python3.9/site-packages/friendly_traceback/frame_info.py", line 20, in partial_source
    return self._partial_source(with_node_range=False)
  File "/home/mdk/.local/lib/python3.9/site-packages/friendly_traceback/frame_info.py", line 36, in _partial_source
    if not self.lines and self.filename:
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/utils.py", line 141, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/core.py", line 656, in lines
    pieces = self.included_pieces
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/utils.py", line 141, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/core.py", line 622, in included_pieces
    scope_pieces = self.scope_pieces
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/utils.py", line 141, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/core.py", line 559, in scope_pieces
    for piece in self.source.pieces
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/utils.py", line 141, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/core.py", line 86, in pieces
    return list(self._clean_pieces())
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/core.py", line 99, in _clean_pieces
    pieces = [
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/core.py", line 99, in <listcomp>
    pieces = [
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/core.py", line 141, in _raw_split_into_pieces
    for inner_start, inner_end in self._raw_split_into_pieces(sub_stmt, *rang):
  File "/home/mdk/.local/lib/python3.9/site-packages/stack_data/core.py", line 142, in _raw_split_into_pieces
    yield start, inner_start
KeyboardInterrupt  # I had to kill it
```

I reproduced it at least with 0.4.60 and 0.4.53.

**Comment by aroberge** [comment]
@alexmojaki I believe this is a problem with stack_data that I cannot prevent in friendly_traceback.

**Comment by aroberge** [comment]
Not an infinite loop after all ... but a very long time: mroe than 5 minutes (wall clock, while doing something else on my computer)
```
> python ignore.py
time data '2020-01-01' does not match format '%d %m %Y'
no_information: new case to consider.
Friendly_traceback; please_report; new case to consider.

Traceback (most recent call last):
  File "ignore.py", line 6, in <module>
    time.strptime("2020-01-01", "%d %m %Y")
ValueError: time data '2020-01-01' does not match format '%d %m %Y'

        Friendly-traceback does not know the cause of this error.

    A `ValueError` indicates that a function or an operation
    received an argument of the right type, but an inappropriate value.

    No information is known about this exception.
    Please report this example to
    https://github.com/friendly-traceback/friendly-traceback/issues/new
    If you are using a REPL, use `www('bug')` to do so.

    If you are using the Friendly console, use `www()` to
    do an Internet search for this particular case.

    Exception raised on line 6 of file ignore.py.

       2: import friendly_traceback
       4: begin = time.time()
       5: try:
    -->6:     time.strptime("2020-01-01", "%d %m %Y")
       7: except Exception as err:

            time:  <module time (builtin)>
            time.strptime:  <builtin function strptime>

time taken:  334.1140923500061
```

Content of Python file:
```python
import time
import friendly_traceback

begin = time.time()
try:
    time.strptime("2020-01-01", "%d %m %Y")
except Exception as err:
    print(err)
    friendly_traceback.explain_traceback()
print("time taken: ", time.time() - begin)

```

**Comment by alexmojaki** [comment]
Fix is almost there https://github.com/alexmojaki/stack_data/pull/17

**Comment by alexmojaki** [comment]
Fix released! Upgrade and try again.

**Comment by aroberge** [comment]
From 334 seconds down to 0.1 : I call this a wonderful fix.

I'll update the requirements for friendly-traceback and do a new release as well.

Thank you very much @alexmojaki

**Comment by aroberge** [comment]
All tests pass for friendly-traceback (Pyton 3.6 to  latest alpha for 3.11). New version (0.4.61) uploaded to Pypi.

Keeping the issue open for keeping track of this unknown case.

**Comment by JulienPalard** [comment]
/me finds a bug
/me report it
/me goto sleep
/me wakes up
/me stares at everything fixed

Wow thanks @aroberge and @alexmojaki! I checked stack-data 0.1.3 in my non-minimal reproducer and it solves my issue, thanks again!

**Comment by aroberge** [comment]
Explanation added.
```
Friendly-traceback version 0.4.69. [Python version: 3.9.5]
Type 'Friendly' for help on special functions/methods.

[1]: import ignore

Traceback (most recent call last):
  Code block [1], line 1, in <module>
    import ignore
  File "ignore.py", line 2, in <module>
    time.strptime("2020-01-01", "%d %m %Y")
ValueError: time data '2020-01-01' does not match format '%d %m %Y'

[2]: why()

    The value you gave for the time is not in the format you specified.
    Make sure to use the same separator between items
    (for example, between day and month) and keep the order the same
    in both the data provided and the format you specified.


[3]: set_lang('fr')

[4]: why()

    La valeur que vous avez écrite pour le temps n'est pas dans le format que vous avez spécifié.
    Veillez à utiliser le même séparateur entre les éléments
    (par exemple, entre le jour et le mois) et conservez le même ordre
    dans les données fournies et dans le format que vous avez spécifié.
```

**Comment by alexmojaki** [comment]
Suggestion: format datetime.now() and/or an unambiguous datetime in the given format to help them understand what the format means. It's too easy to get confused by e.g. %m and %M. Maybe link to something like https://www.strfti.me/

**Comment by aroberge** [comment]
@alexmojaki Thanks for the suggestion.  While the link you gave would be ideal for an English speaker, I prefer to link to the official Python documentation as it is translated in quite a few languages already.
This is the new addition:
```
The following table might be useful:
https://docs.python.org/3/library/time.html#time.strftime
```
and the French version includes the corresponding link:
```
Le tableau suivant pourrait vous être utile :
https://docs.python.org/fr/3/library/time.html#time.strftime
```

**Comment by alexmojaki** [comment]
You could have different numbers of links for different translations?

**Comment by aroberge** [comment]
@alexmojaki Yes, I probably could.  Or, perhaps I can add something like something like
```
The following site might also be useful: url.
```
and, in French
```
Le site suivant pourrait également être utile: url (anglais seulement)
```
